CREATE TABLE Person (
  ID   NUMERIC      NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  RATE NUMERIC      NOT NULL,
  PRIMARY KEY (ID)
);
INSERT INTO Person (ID, NAME, RATE) VALUES (1, 'Tom', 100.2);
INSERT INTO Person (ID, NAME, RATE) VALUES (2, 'James' , 120);
INSERT INTO Person (ID, NAME, RATE) VALUES (3, 'Anna', 240.5);
